In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("cgpa_package_polynomial_practice.csv")

In [3]:
dataset.head(3)

   cgpa  package
0  4.04     2.28
1  4.13     1.46
2  4.14     2.05

In [4]:
x = dataset.iloc[:,:-1]
y = dataset["package"
            ]

In [9]:
new_data = dataset.head(10)
x_new = new_data.iloc[:,:-1]
y_new = new_data["package"]

In [10]:
from sklearn.model_selection import LeaveOneOut, LeavePOut, KFold, StratifiedKFold

In [12]:
lo = LeaveOneOut()
for train , test in lo.split(x_new,y_new):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]

In [13]:
new_data

   cgpa  package
0  4.04     2.28
1  4.13     1.46
2  4.14     2.05
3  4.14     2.02
4  4.18     2.03
5  4.22     1.91
6  4.25     2.13
7  4.26     1.72
8  4.27     2.26
9  4.35     1.84

In [15]:
lo = LeavePOut(p=2)
for train , test in lo.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[1 3 4 5 6 7 8 9] [0 2]
[1 2 4 5 6 7 8 9] [0 3]
[1 2 3 5 6 7 8 9] [0 4]
[1 2 3 4 6 7 8 9] [0 5]
[1 2 3 4 5 7 8 9] [0 6]
[1 2 3 4 5 6 8 9] [0 7]
[1 2 3 4 5 6 7 9] [0 8]
[1 2 3 4 5 6 7 8] [0 9]
[0 3 4 5 6 7 8 9] [1 2]
[0 2 4 5 6 7 8 9] [1 3]
[0 2 3 5 6 7 8 9] [1 4]
[0 2 3 4 6 7 8 9] [1 5]
[0 2 3 4 5 7 8 9] [1 6]
[0 2 3 4 5 6 8 9] [1 7]
[0 2 3 4 5 6 7 9] [1 8]
[0 2 3 4 5 6 7 8] [1 9]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 3 5 6 7 8 9] [2 4]
[0 1 3 4 6 7 8 9] [2 5]
[0 1 3 4 5 7 8 9] [2 6]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 3 4 5 6 7 9] [2 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 5 6 7 8 9] [3 4]
[0 1 2 4 6 7 8 9] [3 5]
[0 1 2 4 5 7 8 9] [3 6]
[0 1 2 4 5 6 8 9] [3 7]
[0 1 2 4 5 6 7 9] [3 8]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 5 7 8 9] [4 6]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 3 5 6 7 9] [4 8]
[0 1 2 3 5 6 7 8] [4 9]
[0 1 2 3 4 7 8 9] [5 6]
[0 1 2 3 4 6 8 9] [5 7]
[0 1 2 3 4 6 7 9] [5 8]
[0 1 2 3 4 6 7 8] [5 9]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 4 5 7 8] [6 9]
[0 1 2 3 4 5 6 9] [7 8]
[0 1 2 3 4 5 6 8] [7 9]
[0 1 2 3 4 5 6 7] [8 9]

In [16]:
lo = KFold(n_splits=5)
for train , test in lo.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]

In [17]:
# lo = StratifiedKFold()
#StratifiedK-fold works only on classification analysis. So it will not work here.

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [23]:
p = cross_val_score(LinearRegression(),x,y,cv=5)

In [24]:
p.sort()
p*100

array([-272.51505028,   12.07654295,   14.51746974,   25.24357576,
         57.84055429])